"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    question: "How does x402 payment work?",
    answer:
      "When you make a request to QueryFlow, our API returns a 402 Payment Required status with a price quote. Your AI agent signs a payment transaction with its wallet, includes the signature in the request header, and resends. Once we verify payment on Avalanche, we return the data.",
  },
  {
    question: "What cryptocurrencies are supported?",
    answer:
      "QueryFlow currently accepts AVAX on the Avalanche network. We chose Avalanche for its sub-second finality (queries settle in under 2 seconds) and low transaction fees.",
  },
  {
    question: "Do I need to create an account?",
    answer:
      "No! That's the beauty of x402. Your wallet address is your identity. Just connect a wallet, fund it with AVAX, and start querying. No signups, no API keys, no monthly commitments.",
  },
  {
    question: "How accurate are the AI insights?",
    answer:
      "Our insights are generated by aggregating data from multiple sources (CoinGecko, on-chain data, social feeds) and processing them through advanced AI models. Each response includes a confidence score and source citations.",
  },
  {
    question: "Is there a free tier?",
    answer:
      "Yes! Developers get 100 free queries per month on Fuji testnet for development and testing. Production queries on mainnet are pay-per-use starting at $0.01.",
  },
  {
    question: "Can I see all my past queries?",
    answer:
      "Every query is recorded on-chain in our QueryRegistry smart contract. You can view your query history through our dashboard or directly on Snowtrace explorer.",
  },
];

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="section-white py-32" id="faq">
      <div className="mx-auto px-6 md:px-8" style={{ maxWidth: "800px" }}>
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2
            className="text-[#0A0A0A] mb-4"
            style={{
              fontSize: "clamp(2rem, 4vw, 3rem)",
              fontWeight: 700,
              lineHeight: 1.2,
            }}
          >
            Frequently Asked Questions
          </h2>
          <p
            className="text-[#4A4A4A] mx-auto"
            style={{ maxWidth: "600px", fontSize: "1.125rem", lineHeight: 1.6 }}
          >
            Everything you need to know about QueryFlow
          </p>
        </div>

        {/* FAQ Items */}
        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="border border-[#E5E5E5] rounded-xl overflow-hidden"
            >
              <button
                onClick={() => toggle(index)}
                className="w-full flex items-center justify-between p-6 text-left bg-white hover:bg-[#FAFAFA] transition-colors"
              >
                <span className="font-semibold text-[#0A0A0A] pr-4">
                  {faq.question}
                </span>
                <ChevronDown
                  size={20}
                  className={`text-[#6A6A6A] shrink-0 transition-transform duration-200 ${
                    openIndex === index ? "rotate-180" : ""
                  }`}
                />
              </button>
              {openIndex === index && (
                <div
                  className="px-6 pb-6 text-[#4A4A4A]"
                  style={{ lineHeight: 1.7 }}
                >
                  {faq.answer}
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
